%YAML 1.2
---
- name: Set SSH log locale for CentOS boxes
  set_fact:
    fail2ban_distro_ssh_log: "{{ fail2ban_centos_ssh_log }}"
  when: fail2ban_distro_ssh_log is not defined

- name: Set auth log locale for CentOS boxes
  set_fact:
    fail2ban_distro_auth_log: "{{ fail2ban_centos_auth_log }}"
  when: fail2ban_distro_auth_log is not defined

- name: Install fail2ban via yum
  yum:
    name:  fail2ban
    state: "{{ 'latest' if fail2ban_pkg_install_latest else 'present' }}"
  notify:
    - restart fail2ban
...
