---
- name: Include CentOS
  include: distros/centos.yml
  when: ansible_pkg_mgr == 'yum'

- name: Include Debian
  include: distros/debian.yml
  when: ansible_pkg_mgr == 'apt'

- name: Include jails
  include: jails.yml

- name: Include filters
  include: filters.yml

- name: Include actions
  include: actions.yml

- name: Put the local jail in place
  template:
    dest:   "{{ fail2ban_localjail_path }}"
    src:    "{{ fail2ban_localjail_template }}"
    owner:  "{{ fail2ban_localjail_owner }}"
    group:  "{{ fail2ban_localjail_group }}"
    mode:   "{{ fail2ban_localjail_mode }}"
  notify:
    - restart fail2ban
  become: "{{ fail2ban_become }}"

...
